CREATE TABLE todos
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    record    VARCHAR(255)                             NOT NULL,
    completed BOOLEAN                                  NOT NULL,
    CONSTRAINT pk_todos PRIMARY KEY (id)
);

CREATE TABLE diaries
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    record    VARCHAR(255)                             NOT NULL,
    date      date                                     NOT NULL,
    completed BOOLEAN                                  NOT NULL,
    CONSTRAINT pk_diaries PRIMARY KEY (id)
);

CREATE TABLE users_diaries
(
    diary_id INTEGER NOT NULL,
    user_id  INTEGER NOT NULL,
    CONSTRAINT pk_users_diaries PRIMARY KEY (diary_id, user_id)
);

CREATE TABLE users_todos
(
    todo_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    CONSTRAINT pk_users_todos PRIMARY KEY (todo_id, user_id)
);

ALTER TABLE users_diaries
    ADD CONSTRAINT fk_usedia_on_diary FOREIGN KEY (diary_id) REFERENCES diaries (id);

ALTER TABLE users_diaries
    ADD CONSTRAINT fk_usedia_on_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE users_todos
    ADD CONSTRAINT fk_usetod_on_todo FOREIGN KEY (todo_id) REFERENCES todos (id);

ALTER TABLE users_todos
    ADD CONSTRAINT fk_usetod_on_user FOREIGN KEY (user_id) REFERENCES users (id);
